### ISSUE TITLE
Spline Math appears Broke on TelemetryProcessor.get_roll()

### ISSUE THREAD

**Issue by b-berry** [b-berry/lg-scripts#1]
```
bryan@b3erry-ephq:~/src/lg-monaco/ocean_acidification$ lg-tour -a roscoe -f spline placemarks-great-barrier-reef.kml -w
Building Placemarks Great Barrier Reef Spline...
...reading KML...
...done.
Generating spline path...
/home/bryan/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/kamelopard-0.0.16/lib/kamelopard/helpers.rb:411:in `acos': Numerical argument is out of domain - "acos" (Math::DomainError)
        from /home/bryan/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/kamelopard-0.0.16/lib/kamelopard/helpers.rb:411:in `get_roll'
        from /home/bryan/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/kamelopard-0.0.16/lib/kamelopard/helpers.rb:438:in `add_flyto'
        from /home/bryan/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/kamelopard-0.0.16/lib/kamelopard/helpers.rb:498:in `block in tour_from_points'
        from /home/bryan/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/kamelopard-0.0.16/lib/kamelopard/helpers.rb:497:in `each'
        from /home/bryan/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/kamelopard-0.0.16/lib/kamelopard/helpers.rb:497:in `tour_from_points'
        from /home/bryan/src/lg-scripts/batchTour.rb:823:in `makeSpline'
        from /home/bryan/src/lg-scripts/batchTour.rb:869:in `makeTour'
        from /home/bryan/src/lg-scripts/batchTour.rb:982:in `<main>'
```

```
396     def TelemetryProcessor.get_roll(p)
397         x1, y1, x2, y2, x3, y3 = [ p[0][0], p[0][1], p[1][0], p[1][1], p[2][0], p[2][1] ]
398         return 0 if x1.nil? or x2.nil?
399 
400         # Measure roll based on angle between P1 -> P2 and P2 -> P3. To be really
401         # exact I ought to take into account altitude as well, but ... I don't want
402         # to
403 
404         # Set x2, y2 as the origin
405         xn1 = x1 - x2
406         xn3 = x3 - x2
407         yn1 = y1 - y2
408         yn3 = y3 - y2
409 
410         # Use dot product to get the angle between the two segments
411         angle = Math.acos( ((xn1 * xn3) + (yn1 * yn3)) / (get_dist2(0, 0, xn1, yn1).abs * get_dist2(0, 0, xn3, yn3).abs) ) * 180 / Math::PI
412 
413         @@options[:exaggerate] * (angle - 180)
414     end
```

**Comment by b-berry** [comment]
- input KML file:

``` kml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
    <name>KmlFile</name>
    <Placemark>
        <name>Great Barrier Reef 0</name>
        <LookAt>
            <gx:TimeSpan>
                <begin>1584-12-13</begin>
                <end>1950</end>
            </gx:TimeSpan>
            <longitude>151.1642664057736</longitude>
            <latitude>-20.63032776757699</latitude>
            <altitude>0</altitude>
            <heading>-75.70142275656016</heading>
            <tilt>41.75222041847768</tilt>
            <range>233878.6498839571</range>
            <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
        </LookAt>
        <Point>
            <coordinates>151.1642664057735,-20.63032776757699,0</coordinates>
        </Point>
    </Placemark>
    <Placemark>
        <name>Great Barrier Reef 1</name>
        <LookAt>
            <longitude>150.0312623254549</longitude>
            <latitude>-19.44475846405832</latitude>
            <altitude>0</altitude>
            <heading>-50.49608234460616</heading>
            <tilt>0.5989708273708421</tilt>
            <range>859784.0410155565</range>
            <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
        </LookAt>
        <Point>
            <coordinates>149.9311556867915,-19.94501185370329,0</coordinates>
        </Point>
    </Placemark>
    <Placemark>
        <name>Great Barrier Reef 2</name>
        <LookAt>
            <longitude>148.3118704674926</longitude>
            <latitude>-18.99926532344006</latitude>
            <altitude>0</altitude>
            <heading>-49.96406730364253</heading>
            <tilt>0.5989937791100216</tilt>
            <range>860026.7724870719</range>
            <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
        </LookAt>
        <Point>
            <coordinates>148.6610024368913,-19.29090992711976,0</coordinates>
        </Point>
    </Placemark>
    <Placemark>
        <name>Great Barrier Reef 3</name>
        <LookAt>
            <longitude>148.3118704674926</longitude>
            <latitude>-18.99926532344006</latitude>
            <altitude>0</altitude>
            <heading>-49.96406730364253</heading>
            <tilt>0.5989937791100216</tilt>
            <range>860026.7724870719</range>
            <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
        </LookAt>
        <Point>
            <coordinates>147.3316893716784,-18.6500407440715,0</coordinates>
        </Point>
    </Placemark>
    <Placemark>
        <name>Great Barrier Reef 4</name>
        <LookAt>
            <longitude>148.3118704674926</longitude>
            <latitude>-18.99926532344006</latitude>
            <altitude>0</altitude>
            <heading>-49.96406730364253</heading>
            <tilt>0.5989937791100216</tilt>
            <range>860026.7724870719</range>
            <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
        </LookAt>
        <Point>
            <coordinates>146.3968111225697,-17.33180139022354,0</coordinates>
        </Point>
    </Placemark>
    <Placemark>
        <name>Great Barrier Reef 5</name>
        <LookAt>
            <longitude>146.9881013951718</longitude>
            <latitude>-15.99112896224607</latitude>
            <altitude>0</altitude>
            <heading>-49.6690171944442</heading>
            <tilt>0.5990366977730254</tilt>
            <range>860484.9232477784</range>
            <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
        </LookAt>
        <Point>
            <coordinates>145.7661096776664,-15.78629589492867,0</coordinates>
        </Point>
    </Placemark>
    <Placemark>
        <name>Great Barrier Reef 6</name>
        <LookAt>
            <longitude>145.7817207979079</longitude>
            <latitude>-13.14293760679148</latitude>
            <altitude>0</altitude>
            <heading>-49.39429766962623</heading>
            <tilt>0.5992298036595787</tilt>
            <range>862535.8087699416</range>
            <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
        </LookAt>
        <Point>
            <coordinates>145.1957928556996,-14.37594475325439,0</coordinates>
        </Point>
    </Placemark>
    <Placemark>
        <name>Great Barrier Reef 7</name>
        <LookAt>
            <longitude>144.2833707209851</longitude>
            <latitude>-13.05027141351474</latitude>
            <altitude>0</altitude>
            <heading>-49.08083951943455</heading>
            <tilt>0.5989774638903764</tilt>
            <range>859853.2808576156</range>
            <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
        </LookAt>
        <Point>
            <coordinates>144.1051953847889,-13.52040231558547,0</coordinates>
        </Point>
    </Placemark>
</Document>
</kml>
```

**Comment by b-berry** [comment]
https://ruby-doc.org/core-1.9.3/Math/DomainError.html
